<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXeuz86p\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXeuz86p/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXeuz86p.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXeuz86p\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXeuz86p\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xeuz86p',
    'container.build_id' => '87bf4b99',
    'container.build_time' => 1536831144,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXeuz86p');
